# Reinforcement Learning ( Using MonteCarlo algorithem to play Black Jack)

## reseting and cleaning the variables and outputs

In [1]:
%reset -f
!rm *

'rm' is not recognized as an internal or external command,
operable program or batch file.


## Importing the Important pyton packages

In [1]:
import gym
import pandas as pd
import random
from collections import defaultdict
import numpy as np

## Creating and testing the Black Jack environment

In [8]:
'''Create a blackjack environment'''
env = gym.make('Blackjack-v1', render_mode='rgb_array')

In [ ]:
print(list(env.reset()))
'''False=  player does not have a usable ace, True= player has usable ace'''


[(8, 10, False), {}]


'False=  player does not have a usable ace, True= player has usable ace'

In [5]:
print(env.action_space)
print(env.observation_space)

Discrete(2)
Tuple(Discrete(32), Discrete(11), Discrete(2))


## Importing the policy to run the game

In [10]:
'''every visit monte carlo'''
'''0 is stand and 1 is hit'''


def policy(state):
    return 0 if state[0] > 19 else 1



num_timesteps = 100

def generate_episode(policy):
    episode = []
    state = list(env.reset()[0])
    for t in range(num_timesteps):
        action = policy(state)
        [next_state, reward, done, info, _]  = env.step(action)
        episode.append([state, action, reward])
        if done:
            episode.append([next_state])
            break
        state = list(next_state)
        
    
    return episode

generated_episode = generate_episode(policy)
print(generated_episode)
print(*generated_episode)

[[[15, 10, False], 1, 0.0], [[17, 10, False], 1, 0.0], [[20, 10, False], 0, 0.0], [(20, 10, False)]]
[[15, 10, False], 1, 0.0] [[17, 10, False], 1, 0.0] [[20, 10, False], 0, 0.0] [(20, 10, False)]


In [11]:
'''working with * to point to the state and rewared and action'''
poped_generated_episode = generated_episode[:-1]
print(poped_generated_episode)
states, actions, rewards = zip(*poped_generated_episode)
print(states)
print(rewards)
print(actions)

[[[15, 10, False], 1, 0.0], [[17, 10, False], 1, 0.0], [[20, 10, False], 0, 0.0]]
([15, 10, False], [17, 10, False], [20, 10, False])
(0.0, 0.0, 0.0)
(1, 1, 0)


In [12]:
'''working with numpy array to point to the state and reward and action'''
a = np.array(poped_generated_episode, dtype=list).transpose()
print(a)
states, actions, rewards = zip(a)
print(states)
print(rewards)
print(actions)

[[list([15, 10, False]) list([17, 10, False]) list([20, 10, False])]
 [1 1 0]
 [0.0 0.0 0.0]]
(array([list([15, 10, False]), list([17, 10, False]),
       list([20, 10, False])], dtype=object),)
(array([0.0, 0.0, 0.0], dtype=object),)
(array([1, 1, 0], dtype=object),)


In [19]:
'''every-visit monte carlo prediction'''
'''if I use 'human' render_mode it consumes a long time to run. Thus, I used 'rgb_array'.'''
def policy(state):
    return 0 if state[0] > 19 else 1

num_timesteps = 100

def generate_episode(policy):
    episode = []
    state = env.reset()[0]
    for t in range(num_timesteps):
        action = policy(state)
        [next_state, reward, done, info, _]  = env.step(action)
        episode.append([state, action, reward])
        if done:
            episode.append([next_state])
            break
        state = next_state
        
        # print(next_value)
    return episode

total_return = defaultdict(float)
N = defaultdict(int)
num_iterations = 50000
for i in range(num_iterations):
    episode = generate_episode(policy)[:-1]
    states, actions, rewards = zip(*episode)
    for t, state in enumerate(states):
        R = (sum(rewards[t:]))
        total_return[state] = total_return[state] + R
        N[state] = N[state] + 1
total_return = pd.DataFrame(total_return.items(),columns=['state', 'total_return'])
N = pd.DataFrame(N.items(),columns=['state', 'N'])
df = pd.merge(total_return, N, on="state")
df['value'] = df['total_return']/df['N']
df.head(50)

state  total_return     N     value
0    (12, 10, True)         -34.0   116 -0.293103
1    (15, 10, True)         -72.0   206 -0.349515
2   (15, 10, False)       -1302.0  1979 -0.657908
3   (18, 10, False)       -1572.0  2124 -0.740113
4    (17, 1, False)        -407.0   560 -0.726786
5    (20, 1, False)         128.0   778  0.164524
6    (12, 2, False)        -234.0   451 -0.518847
7    (18, 2, False)        -376.0   505 -0.744554
8   (10, 10, False)        -190.0   793 -0.239596
9   (20, 10, False)        1310.0  2950  0.444068
10   (13, 9, False)        -264.0   475 -0.555789
11    (21, 6, True)         209.0   215  0.972093
12   (14, 3, False)        -275.0   455 -0.604396
13   (21, 3, False)         349.0   389  0.897172
14    (9, 5, False)         -83.0   160 -0.518750
15   (16, 5, False)        -331.0   529 -0.625709
16    (21, 4, True)         238.0   244  0.975410
17   (9, 10, False)        -368.0   592 -0.621622
18  (14, 10, False)       -1242.0  1882 -0.659936
19   (21, 9, False)         383.0   407  0.941032
20    (6, 6, False)         -35.0    80 -0.437500
21   (13, 6, False)        -284.0   494 -0.574899
22   (18, 6, False)        -366.0   547 -0.669104
23   (21, 6, False)         346.0   390  0.887179
24   (13, 3, False)        -277.0   477 -0.580713
25    (21, 1, True)         151.0   231  0.653680
26   (14, 1, False)        -351.0   495 -0.709091
27   (17, 3, False)        -348.0   495 -0.703030
28   (13, 2, False)        -282.0   472 -0.597458
29   (19, 2, False)        -391.0   541 -0.722736
30   (12, 1, False)        -285.0   423 -0.673759
31   (15, 1, False)        -389.0   536 -0.725746
32   (16, 2, False)        -370.0   496 -0.745968
33   (20, 7, False)         591.0   743  0.795424
34   (18, 1, False)        -423.0   548 -0.771898
35  (19, 10, False)       -1670.0  2230 -0.748879
36   (11, 7, False)           7.0   222  0.031532
37   (21, 7, False)         380.0   406  0.935961
38   (11, 6, False)         -20.0   214 -0.093458
39   (14, 6, False)        -305.0   491 -0.621181
40   (21, 10, True)         894.0   980  0.912245
41   (13, 10, True)         -65.0   206 -0.315534
42  (13, 10, False)       -1096.0  1855 -0.590836
43    (21, 3, True)         219.0   227  0.964758
44   (17, 5, False)        -327.0   484 -0.675620
45    (8, 6, False)         -77.0   144 -0.534722
46   (10, 6, False)         -39.0   182 -0.214286
47   (17, 6, False)        -349.0   533 -0.654784
48   (20, 3, False)         441.0   737  0.598372
49    (19, 4, True)         -35.0    92 -0.380435

In [20]:
'''epsilon-greedy monte carlo on_policy control'''
'''Initialize the dictionary for storing the Q values'''

Q = defaultdict(float)
total_return = defaultdict(float)
N = defaultdict(int)

'''Define the epsilon-greedy policy'''

def epsilon_greedy_policy(state,Q):
    epsilon = 0.9
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x: Q[(state,x)])
            
'''Generating an episode'''
num_timesteps = 100
def generate_episode(Q):
    episode = []
    state = env.reset()[0]
    for t in range(num_timesteps):
        action = epsilon_greedy_policy(state,Q)
        [next_state, reward, done, info, _]  = env.step(action)
        episode.append([state, action, reward])
        if done:
            break
        state = next_state
    return episode



'''Computing the optimal policy'''
num_iterations = 50000
for i in range(num_iterations):
    episode = generate_episode(Q)
    all_state_action_pairs = [(s, a) for (s,a,r) in episode]
    rewards = [r for (s,a,r) in episode]
    for t, (state, action,_) in enumerate(episode):
        if not (state, action) in all_state_action_pairs[0:t]:
            R = sum(rewards[t:])
            total_return[(state,action)] = total_return[(state,action)] + R
            N[(state, action)] += 1
            Q[(state,action)] = total_return[(state, action)] / N[(state, action)]
df = pd.DataFrame(Q.items(),columns=['state_action pair','value'])
df.head(60)

state_action pair     value
0     ((18, 7, True), 0)  0.342857
1     ((13, 2, True), 1) -0.076923
2    ((13, 2, False), 0) -0.238095
3   ((20, 10, False), 1) -0.944568
4   ((12, 10, False), 0) -0.632391
5    ((14, 7, False), 1) -0.534091
6    ((16, 7, False), 0) -0.542857
7    ((14, 3, False), 0) -0.223881
8   ((18, 10, False), 0) -0.245658
9   ((10, 10, False), 0) -0.580952
10   ((15, 6, False), 1) -0.475904
11   ((17, 6, False), 1) -0.677778
12   ((18, 6, False), 0)  0.268657
13   ((14, 10, True), 1) -0.440860
14   ((15, 10, True), 1) -0.575221
15  ((15, 10, False), 0) -0.597647
16   ((17, 6, False), 0) -0.060773
17   ((19, 6, False), 1) -0.847059
18   ((14, 9, False), 0) -0.468085
19    ((9, 1, False), 1) -0.720930
20   ((13, 1, False), 1) -0.753363
21   ((19, 1, False), 1) -0.842105
22   ((12, 6, False), 0) -0.146667
23    ((9, 6, False), 0) -0.047619
24   ((15, 8, False), 0) -0.457143
25   ((15, 3, False), 0) -0.252525
26   ((15, 3, False), 1) -0.664634
27    ((15, 1, True), 0) -0.777778
28   ((15, 5, False), 0) -0.167513
29   ((15, 5, False), 1) -0.680982
30   ((17, 5, False), 0) -0.052632
31   ((18, 3, False), 0)  0.105820
32   ((21, 10, True), 1) -0.410714
33  ((21, 10, False), 1) -1.000000
34    ((6, 1, False), 0) -0.875000
35  ((13, 10, False), 0) -0.569462
36   ((20, 8, False), 0)  0.756250
37   ((14, 5, False), 0) -0.179487
38   ((15, 9, False), 1) -0.726744
39    ((20, 6, True), 0)  0.585366
40    ((20, 6, True), 1)  0.030303
41   ((8, 10, False), 1) -0.518519
42  ((18, 10, False), 1) -0.808777
43   ((8, 10, False), 0) -0.522267
44  ((14, 10, False), 0) -0.610294
45  ((13, 10, False), 1) -0.638441
46  ((17, 10, False), 1) -0.771518
47   ((16, 2, False), 1) -0.690476
48  ((12, 10, False), 1) -0.629405
49  ((15, 10, False), 1) -0.732249
50  ((14, 10, False), 1) -0.663978
51  ((20, 10, False), 0)  0.454545
52   ((13, 7, False), 0) -0.447699
53   ((13, 8, False), 0) -0.484979
54   ((9, 10, False), 1) -0.467456
55  ((16, 10, False), 1) -0.720567
56   ((20, 4, False), 0)  0.644444
57   ((18, 9, False), 0) -0.207373
58   ((15, 10, True), 0) -0.600000
59   ((13, 10, True), 1) -0.362637

In [7]:
env.close()